# Generated by Django 5.0.3 on 2024-03-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('sare', 'sare'), ('poshak', 'poshak'), ('lehenga', 'lehenga')], max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dresses/')),
            ],
        ),
        migrations.CreateModel(
            name='Jewellry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dresses/')),
            ],
        ),
    ]
