# Generated by Django 5.0.2 on 2024-03-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dress',
            name='name',
        ),
        migrations.AddField(
            model_name='dress',
            name='category',
            field=models.CharField(blank=True, choices=[("Women's", "Women's"), ("Men's", "Men's"), ("Kid's", "Kid's")], max_length=250, null=True),
        ),
    ]
