# Generated by Django 5.0.2 on 2024-03-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_dress_name_dress_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewellry',
            name='name',
        ),
        migrations.AddField(
            model_name='jewellry',
            name='category',
            field=models.CharField(blank=True, choices=[('Bracelets', 'Braceletss'), ('Kada', 'kada'), ('Necklace', 'Necklace'), ('Earrings', 'Earrings')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jewellry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='jewellry/'),
        ),
    ]
